openhpc_cluster_name: "{{ cluster_name }}"

# Provision a single "standard" compute partition using the supplied
# node count and flavor
openhpc_slurm_partitions: "{{ hostvars[groups['openstack'][0]]['openhpc_slurm_partitions'] }}"
