---
roles:
  - src: stackhpc.nfs
    version: v22.9.1
  - src: https://github.com/stackhpc/ansible-role-openhpc.git
    version: v0.20.0 # Allow multiple empty partitions by @sjpb in #156
    name: stackhpc.openhpc
  - src: https://github.com/stackhpc/ansible-node-exporter.git
    version: c9ec08364b91d4097168528699829e6c9c0d38b6 # stackhpc-fixes
    name: cloudalchemy.node_exporter
  - src: https://github.com/cloudalchemy/ansible-prometheus.git
    version: 4d2c8d742de39e50387e0aa6d5510b21c7451343 # need fix in preceeding commit for rocky
    name: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
    version: 0.19.1
  - src: https://github.com/stackhpc/ansible-grafana.git
    name: cloudalchemy.grafana
    version: 27b57570400deda29dbe32ddcb07558f4e957e4e # service-state
  - src: https://github.com/OSC/ood-ansible.git
    name: osc.ood
    version: v2.0.8

collections:
  - name: containers.podman
    version: 1.10.2
  - name: community.grafana
    version: 1.5.4
  - name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
    type: git
    version: v0.2.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.netcommon
    version: 5.1.1
  - name: community.general
    version: 7.1.0
  - name: community.crypto
    version: 2.10.0
  - name: community.mysql
    version: 3.7.2
  - name: openstack.cloud
    version: 2.1.0
  - name: https://github.com/stackhpc/ansible-collection-terraform
    type: git
    version: 1a8f5af0239de2bfedb37f51e20d973e05699b8a # main @ 20230627
