openhpc_cluster_name: "{{ cluster_name }}"

# Provision a single "standard" compute partition using the supplied
# node count and flavor
openhpc_slurm_partitions:
  - name: "standard"
    count: "{{ compute_count }}"
    flavor_name: "{{ compute_flavor }}"
    default: "YES"
