---

image_build_terraform_project_path: "{{ playbook_dir }}/terraform-caas-image-build"
image_build_cluster_name: "caas-image-build"
cluster_name: "{{ image_build_cluster_name }}"
cluster_id: "{{ image_build_cluster_name }}"

# Regex to capture existing cloud image names to use as the
# OpenHPC Slurm base-image
image_build_existing_image_regex: "^Rocky-8-GenericCloud-Base-8.8-.*"
# Attributes to sort the list of existing base images returned by
# image_build_existing_image_regex. See
# https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/data-sources/images_image_ids_v2#sort
image_build_existing_image_sort_attributes: "name,updated_at"
