---
# Attach a floating IP to the Packer build instance
image_build_attach_floating_ip: false

# Use a volume for the root disk of the Packer build instance
image_build_use_blockstorage_volume: false

# Packer image format (only used when image_build_use_blockstorage_volume: true
image_build_image_disk_format: "qcow2"

# Metadata items to set on the Packer image
image_build_metadata: {}

# The directory that contains the openstack.pkr.hcl to build the Slurm image
image_build_packer_root_path: "{{ playbook_dir }}/vendor/stackhpc/ansible-slurm-appliance/packer"

# The appliances_environment_root directory. This may contain a hooks directory
# optionally containing pre.yml, post-bootstrap.yml and post.yml playbooks, to
# run during the image-build process
image_build_appliances_environment_root: "{{ playbook_dir }}/image-build"

# Vars to apply to the builder group
image_build_builder_group_vars:
  update_log_path: /tmp/update_log
  appliances_repository_root: "{{ playbook_dir }}/vendor/stackhpc/ansible-slurm-appliance"

# ansible_ssh_common_args for Packer build
image_build_ansible_ssh_common_args: >-
    {% if image_build_ssh_bastion_host is defined %}
    '-o ProxyCommand="ssh -W %h:%p -q
    {% if image_build_ssh_bastion_private_key_file is defined %}
    -i {{ image_build_ssh_bastion_private_key_file }}
    {% endif %}
    -l {{ image_build_ssh_bastion_username }}
    {{ image_build_ssh_bastion_host }}"'
    {% else %}
    ""
    {% endif %}
